import React from "react";
import { Link, Routes, Route } from "react-router-dom";

const CONTACT_EMAIL = "bericksse@gmail.com";
const BERICK_PHONE = "+27 82 785 9743";
const TEBOGO_PHONE = "+27 83 305 5303";
const TEBOGO_EMAIL = "tebogoa@gmail.com";
const ADDRESS = "19 Richards Drive, Midrand";

const navItems = [
  ["Home", "/"],
  ["Staffing", "/staffing"],
  ["Training", "/training"],
  ["Customer Experience", "/customer-experience"],
  ["About", "/about"],
  ["FAQ", "/faq"],
];

function Header() {
  return (
    <header className="sticky top-0 z-50 border-b border-slate-200 bg-white">
      <div className="mx-auto flex h-[124px] max-w-7xl items-center justify-between px-6 lg:px-8">
        <Link to="/" className="relative flex h-[124px] w-[360px] shrink-0 items-center overflow-visible">
          <img src="/esp%20logo%203%20modern.png" alt="ESP Exceptional Service Personnel" className="absolute left-[-45px] top-1/2 h-[360px] w-[360px] -translate-y-1/2 object-contain" />
        </Link>
        <nav className="hidden items-center gap-7 lg:flex">
          {navItems.map(([label, path]) => <Link key={path} to={path} className="text-sm font-semibold text-slate-700 transition hover:text-[#f28c28]">{label}</Link>)}
          <Link to="/contact" className="rounded-full bg-[#f28c28] px-7 py-3.5 text-sm font-bold text-white shadow-sm transition hover:bg-[#d97516]">Get in Touch</Link>
        </nav>
        <Link to="/contact" className="rounded-full bg-[#f28c28] px-5 py-3 text-sm font-bold text-white lg:hidden">Contact</Link>
      </div>
    </header>
  );
}

function Footer() {
  return (
    <footer className="bg-[#020817] text-white">
      <div className="mx-auto max-w-7xl px-6 py-16 lg:px-8">
        <div className="grid gap-12 md:grid-cols-2 lg:grid-cols-4">
          <div>
            <Link to="/" className="inline-flex items-center"><img src="/esp%20logo%203%20modern.png" alt="ESP Exceptional Service Personnel" className="h-[190px] w-[190px] object-contain" /></Link>
            <p className="mt-4 max-w-sm text-sm leading-7 text-slate-400">Professional hospitality staffing, practical training and customer experience solutions built around exceptional service.</p>
          </div>
          <div>
            <h3 className="mb-5 text-sm font-bold uppercase tracking-wider text-[#f28c28]">Services</h3>
            <div className="space-y-3 text-sm text-slate-400"><Link to="/staffing" className="block transition hover:text-white">Hospitality Staffing</Link><Link to="/training" className="block transition hover:text-white">Staff Training</Link><Link to="/customer-experience" className="block transition hover:text-white">Customer Experience</Link></div>
          </div>
          <div>
            <h3 className="mb-5 text-sm font-bold uppercase tracking-wider text-[#f28c28]">Company</h3>
            <div className="space-y-3 text-sm text-slate-400"><Link to="/" className="block transition hover:text-white">Home</Link><Link to="/about" className="block transition hover:text-white">About ESP</Link><Link to="/faq" className="block transition hover:text-white">FAQ</Link><Link to="/contact" className="block transition hover:text-white">Contact</Link></div>
          </div>
          <div>
            <h3 className="mb-5 text-sm font-bold uppercase tracking-wider text-[#f28c28]">Contact</h3>
            <p className="text-sm font-semibold text-white">Let's talk about your service.</p>
            <a href={`tel:${BERICK_PHONE.replace(/\s/g, "")}`} className="mt-4 block text-sm text-slate-300 hover:text-[#f28c28]">Berick: {BERICK_PHONE}</a>
            <a href={`mailto:${CONTACT_EMAIL}`} className="mt-2 block break-all text-sm text-slate-400 hover:text-[#f28c28]">{CONTACT_EMAIL}</a>
            <p className="mt-5 text-sm font-semibold text-white">Tebogo Mhlongo</p>
            <a href={`tel:${TEBOGO_PHONE.replace(/\s/g, "")}`} className="mt-1 block text-sm text-slate-400 hover:text-[#f28c28]">{TEBOGO_PHONE}</a>
            <a href={`mailto:${TEBOGO_EMAIL}`} className="mt-1 block break-all text-sm text-slate-400 hover:text-[#f28c28]">{TEBOGO_EMAIL}</a>
            <p className="mt-5 text-sm leading-7 text-slate-400">{ADDRESS}<br />Serving businesses and events across Gauteng.</p>
          </div>
        </div>
        <div className="mt-14 border-t border-slate-800 pt-8 text-sm text-slate-500"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><span>© {new Date().getFullYear()} Exceptional Service Personnel. All rights reserved.</span><a href={`mailto:${CONTACT_EMAIL}`} className="transition hover:text-[#f28c28]">{CONTACT_EMAIL}</a></div></div>
      </div>
    </footer>
  );
}

function PageHero({ eyebrow, title, intro }) {
  return <section className="bg-[#020817] py-20 sm:py-24"><div className="mx-auto max-w-7xl px-6 lg:px-8"><div className="max-w-4xl"><p className="text-sm font-bold uppercase tracking-[0.18em] text-[#f28c28]">{eyebrow}</p><h1 className="mt-5 text-5xl font-black leading-tight tracking-tight text-white sm:text-6xl">{title}</h1><p className="mt-7 max-w-3xl text-lg leading-8 text-slate-300">{intro}</p></div></div></section>;
}
function CTA({ title = "Let's improve your customer experience.", text = "Tell us what you need and we can discuss the right solution for your business, team or event." }) {
  return <section className="bg-slate-50 py-20"><div className="mx-auto max-w-4xl px-6 text-center lg:px-8"><h2 className="text-4xl font-black text-[#020817] sm:text-5xl">{title}</h2><p className="mx-auto mt-5 max-w-2xl text-lg leading-8 text-slate-600">{text}</p><Link to="/contact" className="mt-8 inline-flex rounded-full bg-[#f28c28] px-8 py-4 font-bold text-white transition hover:bg-[#d97516]">Get in Touch →</Link></div></section>;
}

function Home() {
  return <><Header /><main>
    <section className="relative min-h-[680px] overflow-hidden bg-[#020817]"><div className="absolute inset-y-0 right-0 w-full lg:w-[62%]"><img src="/esp-hero-final.png" alt="Professional hospitality waiter serving guests" className="absolute inset-0 h-full w-full object-cover object-center" /><div className="absolute inset-0 bg-gradient-to-r from-[#020817]/90 via-[#020817]/35 via-25% to-transparent" /></div><div className="relative z-10 mx-auto flex min-h-[680px] max-w-7xl items-center px-6 py-20 lg:px-8"><div className="max-w-2xl"><div className="mb-6 inline-flex rounded-full border border-[#f28c28]/40 bg-[#f28c28]/10 px-4 py-2 text-xs font-bold uppercase tracking-[0.18em] text-[#f28c28]">Five-Star Customer Experience</div><h1 className="text-5xl font-black leading-[0.98] tracking-tight text-white sm:text-6xl lg:text-7xl">Exceptional<span className="block">Service</span><span className="mt-3 block">Starts With</span><span className="block text-[#f28c28]">Exceptional</span><span className="block text-[#f28c28]">People.</span></h1><p className="mt-8 max-w-xl text-lg leading-8 text-slate-300">Professional hospitality staffing, practical training and customer experience solutions for businesses and events across Gauteng.</p><div className="mt-9 flex flex-col gap-4 sm:flex-row"><Link to="/staffing" className="inline-flex items-center justify-center rounded-full bg-[#f28c28] px-7 py-4 text-sm font-bold text-white shadow-lg transition hover:bg-[#d97516]">Hire Hospitality Staff <span className="ml-3 text-lg">→</span></Link><Link to="/training" className="inline-flex items-center justify-center rounded-full border border-white/30 bg-white/5 px-7 py-4 text-sm font-bold text-white backdrop-blur-sm transition hover:bg-white/10">Train Your Team</Link></div></div></div></section>
    <section className="border-b border-slate-200 bg-white"><div className="mx-auto grid max-w-7xl grid-cols-2 divide-x divide-slate-200 lg:grid-cols-4"><TrustItem number="2007" label="Established" /><TrustItem number="250+" label="Trained Personnel" /><TrustItem number="Gauteng" label="Service Area" /><TrustItem number="5-Star" label="Service Focus" /></div></section>
    <section className="bg-white py-24"><div className="mx-auto max-w-7xl px-6 lg:px-8"><div className="grid gap-16 lg:grid-cols-2 lg:items-center"><div><p className="mb-4 text-sm font-bold uppercase tracking-[0.18em] text-[#f28c28]">More Than Staffing</p><h2 className="text-4xl font-black tracking-tight text-[#020817] sm:text-5xl">Service is not just what your customers receive.<span className="block text-[#f28c28]">It is how they remember you.</span></h2></div><div><p className="text-lg leading-8 text-slate-600">ESP combines practical hospitality experience with a customer-first approach to help businesses create service experiences that people remember for the right reasons.</p><p className="mt-6 text-lg leading-8 text-slate-600">Whether you need reliable hospitality personnel, want to improve your team's service standards, or are looking to build a stronger customer experience culture, our approach is practical, professional and focused on results.</p><Link to="/customer-experience" className="mt-8 inline-flex font-bold text-[#020817] transition hover:text-[#f28c28]">Explore Customer Experience <span className="ml-3 text-[#f28c28]">→</span></Link></div></div></div></section>
    <section className="bg-slate-50 py-24"><div className="mx-auto max-w-7xl px-6 lg:px-8"><p className="mb-4 text-sm font-bold uppercase tracking-[0.18em] text-[#f28c28]">What We Do</p><h2 className="text-4xl font-black text-[#020817] sm:text-5xl">Practical solutions for better service.</h2><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-600">From the people on the floor to the standards behind the scenes, we help businesses build stronger customer experiences.</p><div className="mt-14 grid gap-7 md:grid-cols-3"><ServiceCard number="01" title="Hospitality Staffing" text="Professional hospitality personnel for restaurants, events, venues and customer-facing operations." link="/staffing" /><ServiceCard number="02" title="Team Training" text="Practical, hands-on training designed to improve service standards, confidence and consistency." link="/training" /><ServiceCard number="03" title="Customer Experience" text="Identify service gaps and create a stronger customer journey from first contact to final impression." link="/customer-experience" /></div></div></section>
    <section className="bg-[#020817] py-24"><div className="mx-auto max-w-5xl px-6 text-center lg:px-8"><p className="text-sm font-bold uppercase tracking-[0.18em] text-[#f28c28]">Ready to Improve Your Service?</p><h2 className="mt-5 text-4xl font-black text-white sm:text-5xl">Let's create a customer experience<span className="block text-[#f28c28]">your business can be proud of.</span></h2><p className="mx-auto mt-6 max-w-2xl text-lg leading-8 text-slate-400">Tell us what you need and we can discuss the right solution for your business, team or event.</p><Link to="/contact" className="mt-9 inline-flex rounded-full bg-[#f28c28] px-8 py-4 font-bold text-white transition hover:bg-[#d97516]">Get in Touch →</Link></div></section>
  </main><Footer /></>;
}

function TrustItem({ number, label }) { return <div className="px-5 py-8 text-center sm:px-8"><div className="text-2xl font-black text-[#020817]">{number}</div><div className="mt-1 text-xs font-bold uppercase tracking-wider text-slate-500">{label}</div></div>; }
function ServiceCard({ number, title, text, link }) { return <Link to={link} className="group border border-slate-200 bg-white p-8 transition hover:-translate-y-1 hover:border-[#f28c28]/40 hover:shadow-xl"><div className="text-sm font-black text-[#f28c28]">{number}</div><h3 className="mt-5 text-2xl font-black text-[#020817]">{title}</h3><p className="mt-4 leading-7 text-slate-600">{text}</p><span className="mt-7 inline-flex font-bold text-[#020817] group-hover:text-[#f28c28]">Learn more →</span></Link>; }

function Staffing() { return <><Header /><PageHero eyebrow="Hospitality Staffing" title="Professional people when you need them." intro="ESP provides reliable, professional hospitality personnel for restaurants, events, venues and other customer-facing operations across Gauteng." /><section className="bg-white py-24"><div className="mx-auto max-w-7xl px-6 lg:px-8"><div className="grid gap-14 lg:grid-cols-2"><div><p className="text-sm font-bold uppercase tracking-[0.18em] text-[#f28c28]">The Right People</p><h2 className="mt-4 text-4xl font-black text-[#020817]">Staff who understand that service matters.</h2><p className="mt-6 text-lg leading-8 text-slate-600">Good hospitality is about more than filling a shift. The people representing your business need to be professional, presentable, dependable and focused on the guest.</p><p className="mt-5 text-lg leading-8 text-slate-600">ESP has built its staffing approach around practical hospitality knowledge and clear service expectations.</p></div><div className="grid gap-5 sm:grid-cols-2"><Feature title="Waiters & Service Staff" text="Professional front-of-house personnel for restaurants, functions and events." /><Feature title="Barmen" text="Confident, professional bar personnel who understand service, presentation and guest interaction." /><Feature title="Event Personnel" text="Flexible staffing support for conferences, functions, launches and special events." /><Feature title="Ongoing Support" text="Staffing solutions can be arranged for once-off requirements or ongoing operations." /></div></div></div></section><CTA title="Need professional hospitality staff?" text="Tell us about your operation, event or staffing requirement and we will discuss the best way to support you." /></>; }
function Feature({ title, text }) { return <div className="border border-slate-200 p-7"><h3 className="text-xl font-black text-[#020817]">{title}</h3><p className="mt-3 leading-7 text-slate-600">{text}</p></div>; }

function Training() { return <><Header /><PageHero eyebrow="Professional Training" title="Build a team that knows what exceptional service looks like." intro="Practical service training designed to improve confidence, professionalism, consistency and the way your team interacts with customers." /><section className="bg-white py-24"><div className="mx-auto max-w-7xl px-6 lg:px-8"><div className="max-w-3xl"><p className="text-sm font-bold uppercase tracking-[0.18em] text-[#f28c28]">Training That Transfers to the Floor</p><h2 className="mt-4 text-4xl font-black text-[#020817]">Less theory. More practical service.</h2><p className="mt-6 text-lg leading-8 text-slate-600">Our training is built around the situations your staff actually face. The objective is not simply to complete a training session; it is to improve behaviour and service standards where customers experience them.</p></div><div className="mt-14 grid gap-6 md:grid-cols-2 lg:grid-cols-3"><TrainingCard title="Service Excellence" text="Professional standards, service mindset, presentation and consistency." /><TrainingCard title="Guest Interaction" text="Confident communication, anticipation of needs and creating positive impressions." /><TrainingCard title="Restaurant Service" text="Practical front-of-house standards, table service and team coordination." /><TrainingCard title="Bar Service" text="Professional bar service, guest interaction and responsible service standards." /><TrainingCard title="Upselling" text="Natural, customer-focused techniques that improve the guest experience and revenue opportunity." /><TrainingCard title="Complaints & Recovery" text="How to handle difficult situations professionally and turn service problems into recovery opportunities." /></div></div></section><CTA title="Ready to strengthen your team?" text="We can tailor training around your operation, your standards and the service challenges you want to improve." /></>; }
function TrainingCard({ title, text }) { return <div className="border border-slate-200 bg-slate-50 p-7"><h3 className="text-xl font-black text-[#020817]">{title}</h3><p className="mt-3 leading-7 text-slate-600">{text}</p></div>; }

function CustomerExperience() { return <><Header /><PageHero eyebrow="Customer Experience" title="Your customer experience is your reputation." intro="ESP helps customer-facing businesses identify service gaps, strengthen their teams and create a more consistent experience from first contact to final impression." /><section className="bg-white py-24"><div className="mx-auto max-w-7xl px-6 lg:px-8"><div className="grid gap-16 lg:grid-cols-2"><div><p className="text-sm font-bold uppercase tracking-[0.18em] text-[#f28c28]">The Bigger Picture</p><h2 className="mt-4 text-4xl font-black text-[#020817]">Every interaction tells your customer what your business stands for.</h2><p className="mt-6 text-lg leading-8 text-slate-600">Customer experience is not limited to the moment a guest receives their meal or walks through an event. It starts with the first interaction and continues through every touchpoint.</p><p className="mt-5 text-lg leading-8 text-slate-600">We look at the practical details that influence service: people, communication, standards, consistency and the overall customer journey.</p></div><div className="space-y-5"><Feature title="Identify Service Gaps" text="Understand where service breaks down and where small improvements can make a meaningful difference." /><Feature title="Strengthen Standards" text="Create clear expectations for how customers should be welcomed, served, assisted and remembered." /><Feature title="Develop Your People" text="Give staff the confidence and practical skills to deliver better service consistently." /><Feature title="Create Consistency" text="Build service habits that support your brand regardless of who is serving the customer." /></div></div></div></section><CTA title="Let's make your service stand out." /></>; }

function About() { return <><Header /><PageHero eyebrow="About ESP" title="Experience matters. So does the standard you set." intro="Exceptional Service Personnel was established in 2007 and is built on practical hospitality experience, professional people and a belief that exceptional service should be deliberate—not accidental." /><section className="bg-white py-24"><div className="mx-auto max-w-7xl px-6 lg:px-8"><div className="grid gap-16 lg:grid-cols-2"><div><p className="text-sm font-bold uppercase tracking-[0.18em] text-[#f28c28]">Our Foundation</p><h2 className="mt-4 text-4xl font-black text-[#020817]">Hospitality experience with a customer-first mindset.</h2><p className="mt-6 text-lg leading-8 text-slate-600">ESP brings together more than 25 years of industry experience with a practical understanding of what it takes to deliver professional service.</p><p className="mt-5 text-lg leading-8 text-slate-600">From staffing and training to broader customer-experience improvement, our focus remains the same: helping businesses create teams and service standards that customers can trust.</p></div><div className="grid gap-5 sm:grid-cols-2"><Stat number="2007" label="ESP established" /><Stat number="25+" label="Years of industry experience" /><Stat number="250+" label="Trained hospitality personnel" /><Stat number="Gauteng" label="Core service area" /></div></div></div></section><section className="bg-slate-50 py-20"><div className="mx-auto max-w-4xl px-6 text-center lg:px-8"><p className="text-sm font-bold uppercase tracking-[0.18em] text-[#f28c28]">What We Believe</p><h2 className="mt-4 text-4xl font-black text-[#020817]">Professional service is a business advantage.</h2><p className="mt-6 text-lg leading-8 text-slate-600">The strongest customer experiences come from people who know what is expected, have the confidence to deliver it and understand why every interaction matters.</p></div></section><CTA title="Talk to ESP about your service standards." /></>; }
function Stat({ number, label }) { return <div className="border border-slate-200 bg-slate-50 p-7"><div className="text-3xl font-black text-[#020817]">{number}</div><p className="mt-2 text-sm font-semibold uppercase tracking-wide text-slate-500">{label}</p></div>; }

const faqs = [
  ["How long has ESP been operating?", "ESP was established in 2007 and has built its experience around hospitality staffing, service and customer-facing operations."],
  ["How many staff does ESP supply?", "ESP has trained more than 250 hospitality and event personnel."],
  ["Does ESP supply Gallagher Convention Centre?", "Yes. ESP has supplied hospitality staff to Gallagher Convention Centre continuously since 2007."],
  ["Where does ESP operate?", "ESP operates across Johannesburg, Pretoria, Midrand, Centurion and the greater Gauteng area."],
  ["What types of businesses can ESP assist?", "Our services are suited to restaurants, events, venues, hospitality operations and other businesses where customer experience and professional service matter."],
  ["Can training be tailored to our business?", "Yes. Training can be structured around your operation, team, service standards and the areas you want to improve."],
];
function FAQ() { return <><Header /><PageHero eyebrow="Frequently Asked Questions" title="Straight answers about ESP." intro="A few of the questions we are most often asked about our experience, staffing and service solutions." /><section className="bg-white py-20"><div className="mx-auto max-w-4xl px-6 lg:px-8"><div className="space-y-4">{faqs.map(([q, a]) => <details key={q} className="group border border-slate-200 bg-slate-50 p-6"><summary className="cursor-pointer list-none pr-8 text-lg font-bold text-[#020817]">{q}</summary><p className="mt-4 leading-7 text-slate-600">{a}</p></details>)}</div></div></section><CTA title="Still have a question?" text="Get in touch with ESP and we will be happy to discuss your requirements." /></>; }

function Contact() { return <><Header /><PageHero eyebrow="Get in Touch" title="Let's talk about your service." intro="Whether you need hospitality staff, team training or help improving your customer experience, contact ESP to discuss your requirements." /><section className="bg-white py-24"><div className="mx-auto max-w-7xl px-6 lg:px-8"><div className="grid gap-12 lg:grid-cols-2"><div><p className="text-sm font-bold uppercase tracking-[0.18em] text-[#f28c28]">Contact ESP</p><h2 className="mt-4 text-4xl font-black text-[#020817]">Tell us what you need.</h2><p className="mt-6 text-lg leading-8 text-slate-600">Give us a brief outline of your staffing, training or customer-experience requirement and we can start the conversation.</p><div className="mt-10 space-y-7"><ContactPerson name="Berick Austin" phone={BERICK_PHONE} email={CONTACT_EMAIL} role="Principal Contact" /><ContactPerson name="Tebogo Mhlongo" phone={TEBOGO_PHONE} email={TEBOGO_EMAIL} role="Contact" /></div><div className="mt-9 border-t border-slate-200 pt-7"><p className="text-sm font-bold uppercase tracking-wider text-slate-500">Address</p><p className="mt-2 text-lg font-semibold text-[#020817]">{ADDRESS}</p><p className="mt-1 text-slate-600">Serving businesses and events across Gauteng.</p></div></div><div className="border border-slate-200 bg-slate-50 p-8"><h3 className="text-2xl font-black text-[#020817]">Contact ESP directly</h3><p className="mt-2 text-slate-600">Choose the contact method that suits you best.</p><div className="mt-8 space-y-4"><a href={`mailto:${CONTACT_EMAIL}`} className="block rounded-lg bg-white p-5 font-bold text-[#020817] shadow-sm transition hover:text-[#f28c28]">Email ESP →<span className="mt-1 block text-sm font-normal text-slate-500">{CONTACT_EMAIL}</span></a><a href={`tel:${BERICK_PHONE.replace(/\s/g, "")}`} className="block rounded-lg bg-white p-5 font-bold text-[#020817] shadow-sm transition hover:text-[#f28c28]">Call Berick →<span className="mt-1 block text-sm font-normal text-slate-500">{BERICK_PHONE}</span></a><a href={`tel:${TEBOGO_PHONE.replace(/\s/g, "")}`} className="block rounded-lg bg-white p-5 font-bold text-[#020817] shadow-sm transition hover:text-[#f28c28]">Call Tebogo →<span className="mt-1 block text-sm font-normal text-slate-500">{TEBOGO_PHONE}</span></a></div></div></div></div></section></> }
function ContactPerson({ name, phone, email, role }) { return <div><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#f28c28]">{role}</p><h3 className="mt-1 text-xl font-black text-[#020817]">{name}</h3><a href={`tel:${phone.replace(/\s/g, "")}`} className="mt-2 block font-semibold text-slate-700 hover:text-[#f28c28]">{phone}</a><a href={`mailto:${email}`} className="mt-1 block text-slate-600 hover:text-[#f28c28]">{email}</a></div>; }
function NotFound() { return <><Header /><section className="bg-[#020817] py-32 text-center text-white"><p className="text-[#f28c28]">404</p><h1 className="mt-3 text-5xl font-black">Page not found.</h1><Link to="/" className="mt-8 inline-flex rounded-full bg-[#f28c28] px-7 py-4 font-bold">Back to Home</Link></section><Footer /></>; }

export default function App() {
  return <Routes><Route path="/" element={<Home />} /><Route path="/staffing" element={<Staffing />} /><Route path="/training" element={<Training />} /><Route path="/customer-experience" element={<CustomerExperience />} /><Route path="/about" element={<About />} /><Route path="/faq" element={<FAQ />} /><Route path="/contact" element={<Contact />} /><Route path="*" element={<NotFound />} /></Routes>;
}
